# Generated by Django 4.2.7 on 2023-11-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('services', models.CharField(blank=True, choices=[('Oil Change', 'Oil Change'), ('Repairs', 'Repairs'), ('Diagnostics', 'Diagnostics'), ('Roadside Assistance', 'Roadside Assistance')], max_length=50, null=True)),
            ],
        ),
    ]
